dynamic handler 의 pipe와 fork 가 잘못 되었을때 500 error 응답을 내보내도록 함
soulee-dev/webserv pull request #101
Opened 2023-08-17 07:09 UTC by bestjinam

2023-08-17 07:43 UTC, CodyKat requested changes

2023-08-17 07:43 UTC, CodyKat commented on srcs/Http/Handler/DynamicHandler.cpp
> +        ErrorHandler::sendReqtoError(client);
에러헨들러로 에러를 보내고 리턴을 하더라도 메시지는 가겠지만 다음 함수들까지 호출되는데 괜찮을까요?
일단 테스트해보니 이벤트에러가 뜨던데 try_catch문으로 밖에서 잡는게 더 좋지 않을까요?

2023-08-17 10:37 UTC, soulee-dev requested changes
try-catch등의 방법을 사용해서 수정 해보도록 하겠습니다.
이후 @bestjinam @CodyKat 두분에게 Review 요청 하도록 하겠습니다.

2023-08-17 10:37 UTC, soulee-dev commented on srcs/Http/Handler/HttpStatusCodes.cpp
> +        STATUS_CODES[501] = "";
501 Not Implemented 메시지가 필요하다고 생각했는데, @bestjinam 물어보니 안쓰신다고 해서 삭제 하겠습니다.

2023-08-17 10:37 UTC, soulee-dev commented on srcs/Http/HttpRequest.hpp
> +        int         errorCode;
int로 바꾼 이유: 기존에는 ParseErrorCode로 파싱 단계에서만 사용 가능했지만, int로 변경함으로써 파싱 이후 단계의 오류에 대해서도 처리가 가능해짐 by @bestjinam

2023-08-18 10:54 UTC, bestjinam reviewed
굿

2023-08-18 10:56 UTC, soulee-dev approved these changes

2023-08-18 10:56 UTC, merged