Feature/http version checker
soulee-dev/webserv pull request #87
Opened 2023-08-15 11:35 UTC by Espebaum

http version 체크하는거, errorhandler 강화된거 커밋합니다

2023-08-15 12:54 UTC, soulee-dev requested changes
구현은 좋습니다! 하지만 에러페이지별 페이지 렌더링을
잼전님이 해주시는거랑 겹치는 부분 있을거 같습니다!
같이 리뷰 부탁드려요~! @CodyKat

2023-08-15 13:01 UTC, CodyKat approved these changes
Look Good for me!!

이전에 말씀드린대로 handler가 client를 가지고 있게 하는 구조로 변경중인데, 이 구조면 쉽게 할 수 있을 것 같습니다.

2023-08-15 13:13 UTC, CodyKat commented
근데 telnet 으로 테스트해보니 한번 505에러가 있던 뒤로 엔터를 칠때마다 해당 에러가 응답으로 전송되는것같은데 초기화 parse state초기화가 안되고 있는지 확인해봐야겠어요

2023-08-15 13:21 UTC, CodyKat commented
parseState는 잘 초기화가 되고 있는데 READY단계에서 request를 push했던것을 에러처리단계에서 pop해주지않아서 잘못된 메시지가 계속 쌓여있는것같습니다

2023-08-15 13:25 UTC, Espebaum commented
확인해보겟습니다~

2023-08-15 13:48 UTC, Espebaum commented
뭔가 문제가 큰것같은데 push랑 pop이 이뤄지는 구조가 눈에 잘안보이네요. 내일 다시확인해봐야할것같습니다... 으악

2023-08-15 13:55 UTC, CodyKat requested changes

2023-08-15 13:55 UTC, CodyKat commented on srcs/Http/Handler/ErrorHandler.cpp
> +std::string find_error_page(int status_code)
여기서는 정적으로 각 40x.html을 파일을 이름으로 넣어주고 있는데 config파일내용을 참조해서 파일을 가져와야할 것 같습니다

2023-08-16 06:45 UTC, Espebaum commented
브랜치 master로 되돌리고 다시 작업합니다..ㅎ

2023-08-16 11:02 UTC, CodyKat approved these changes
우와 너무 멋져요~! 참고로 중간에 제가 allowed method 작업한 함수 코드가 있긴 한데 나중에 마무리 하도록 하겠습니다~!

2023-08-16 11:47 UTC, soulee-dev reviewed
불필요한 디버그 메시지 지우고 제가 머지 하겠습니다.

2023-08-16 11:50 UTC, soulee-dev approved these changes
디버그 메시지 삭제 후 머지 진행 합니다

2023-08-16 11:50 UTC, merged